#ifndef CONFIG_H
#define CONFIG_H

// SUBTOUR PROBLEM PARAMS
#define NUMBER_OF_TARGETS 70

#define POPULATION_SIZE 50
#define TOURNAMENT_SIZE 10
#define MUTATION_RATE 0.6
#define P2OPT_RATE 0.3
#define SOCIAL_DISASTER_RATE 0.1

// GLOBAL PLANNER
#define GLOBAL_PLANNER_RESOURCE_SHARING_BIAS 0.1

#endif